spring.application.name=task1

# Включает веб-консоль H2 для просмотра данных через браузер
spring.h2.console.enabled=true
# Задаёт URL, по которому будет доступна консоль (например, localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Файловая БД: ./data относительно рабочей директории запуска (обычно корень проекта)
# Файлы: data/mydb.mv.db (и при необходимости .trace.db / .lock.db)
spring.datasource.url=jdbc:h2:file:./data/mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Показывать SQL-запросы в консоли IntelliJ IDEA (очень полезно для отладки)
spring.jpa.show-sql=true
# Автоматически обновлять таблицы в БД по модели ваших Java-сущностей (@Entity)
spring.jpa.hibernate.ddl-auto=update
